apiVersion: v1
kind: Service
metadata:
  name: otus-app
  labels:
    app: otus-app
spec:
  selector:
    app: otus-app
  ports:
    - protocol: TCP
      name: metrics
      port: 8000
      targetPort: 8000