apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-app
  labels:
    app: otus-app

spec:
  endpoints:
    - port: metrics
      scheme: http
      interval: 30s
      path: /metrics
#  jobLabel: stack
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: otus-app
  