apiVersion: v1
kind: Service
metadata:
  name: otus-service
  labels:
    app: otus-app
spec:
  type: ClusterIP
  selector:
    app: otus-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: web
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics