apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-monitor
  labels:
    app: metrics-monitor

spec:
  endpoints:
    - port: metrics
      scheme: http
      interval: 30s
      path: /metrics
      honorLabels: true
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: otus-app
  