apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  # Имя Service.
  name: otus-monitor
  labels:
    app: otus
spec:
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 60s
  selector:
    matchLabels:
      app: otus
  namespaceSelector:
    matchNames:
      -production


