apiVersion: v1
kind: Service
metadata:
  # Имя Service.
  name: otus-hw-service
spec:
  type: NodePort
  selector:
    app: otus-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

